package app.casz.notifybridge.ui

import android.app.Activity
import android.content.Context
import android.content.Intent
import android.content.pm.ApplicationInfo
import android.content.pm.PackageManager
import android.os.Bundle
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.Check
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Search
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.window.Dialog
import app.casz.notifybridge.data.local.entity.RuleEntity
import app.casz.notifybridge.data.local.entity.RuleSource
import org.json.JSONObject

class CreateRuleActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val existingRulesCount = intent.getIntExtra(EXTRA_EXISTING_RULES_COUNT, 0)

        setContent {
            NotifyBridgeTheme {
                CreateRuleScreen(
                    existingRulesCount = existingRulesCount,
                    onBack = { finish() },
                    onSaveRule = { rule ->
                        val resultIntent = Intent().apply {
                            putExtra(EXTRA_RULE_NAME, rule.name)
                            putExtra(EXTRA_RULE_SOURCE, rule.source.name)
                            putExtra(EXTRA_APP_PACKAGES, rule.appPackageNames)
                            putExtra(EXTRA_REGEX, rule.regexPattern)
                            putExtra(EXTRA_HTTP_URL, rule.httpUrl)
                            putExtra(EXTRA_HTTP_METHOD, rule.httpMethod)
                            putExtra(EXTRA_HEADERS_JSON, rule.headersJson)
                            putExtra(EXTRA_BODY_TEMPLATE, rule.bodyTemplate)
                        }
                        setResult(Activity.RESULT_OK, resultIntent)
                        finish()
                    }
                )
            }
        }
    }

    companion object {
        const val EXTRA_EXISTING_RULES_COUNT = "extra_existing_rules_count"
        const val EXTRA_RULE_NAME = "extra_rule_name"
        const val EXTRA_RULE_SOURCE = "extra_rule_source"
        const val EXTRA_APP_PACKAGES = "extra_app_packages"
        const val EXTRA_REGEX = "extra_regex"
        const val EXTRA_HTTP_URL = "extra_http_url"
        const val EXTRA_HTTP_METHOD = "extra_http_method"
        const val EXTRA_HEADERS_JSON = "extra_headers_json"
        const val EXTRA_BODY_TEMPLATE = "extra_body_template"
    }
}

data class HeaderInput(val id: Long, var key: String, var value: String)
data class AppItemInfo(val label: String, val packageName: String)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CreateRuleScreen(
    existingRulesCount: Int,
    onBack: () -> Unit,
    onSaveRule: (RuleEntity) -> Unit
) {
    val context = LocalContext.current
    var selectedTab by remember { mutableIntStateOf(0) }

    // State Fields
    val autoGeneratedName = remember { String.format("regla%03d", existingRulesCount + 1) }
    var ruleName by remember { mutableStateOf(autoGeneratedName) }
    var ruleSource by remember { mutableStateOf(RuleSource.APP) }
    var selectedPackages by remember { mutableStateOf(setOf<String>()) }
    var regexPattern by remember { mutableStateOf(".*") }
    var httpUrl by remember { mutableStateOf("https://") }
    var httpMethod by remember { mutableStateOf("POST") }

    // Headers list
    var nextHeaderId by remember { mutableLongStateOf(1L) }
    val headerInputs = remember {
        mutableStateListOf(
            HeaderInput(0L, "Content-Type", "application/json")
        )
    }

    // Body
    var bodyFormat by remember { mutableStateOf("JSON") } // "JSON" or "TEXT"
    var bodyTemplate by remember { mutableStateOf("{\n  \"title\": \"{not_title}\",\n  \"message\": \"{not_text}\"\n}") }

    // Dialog state for app selector
    var showAppPicker by remember { mutableStateOf(false) }

    // Auto-update Content-Type header when body format changes
    fun updateContentType(format: String) {
        val targetType = if (format == "JSON") "application/json" else "text/plain"
        val existingIndex = headerInputs.indexOfFirst { it.key.equals("Content-Type", ignoreCase = true) }
        if (existingIndex != -1) {
            headerInputs[existingIndex] = headerInputs[existingIndex].copy(value = targetType)
        } else {
            headerInputs.add(HeaderInput(nextHeaderId++, "Content-Type", targetType))
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Nueva Regla", fontWeight = FontWeight.Bold) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Atrás")
                    }
                },
                actions = {
                    Button(
                        onClick = {
                            if (ruleName.isBlank()) {
                                Toast.makeText(context, "El nombre de la regla es obligatorio", Toast.LENGTH_SHORT).show()
                                return@Button
                            }
                            if (httpUrl.isBlank()) {
                                Toast.makeText(context, "La URL destino es obligatoria", Toast.LENGTH_SHORT).show()
                                return@Button
                            }

                            // Build Headers JSON
                            val headersMap = mutableMapOf<String, String>()
                            headerInputs.forEach { h ->
                                if (h.key.isNotBlank()) {
                                    headersMap[h.key.trim()] = h.value.trim()
                                }
                            }
                            val headersJson = JSONObject(headersMap as Map<*, *>).toString()

                            val newRule = RuleEntity(
                                name = ruleName.trim(),
                                source = ruleSource,
                                appPackageNames = if (ruleSource == RuleSource.APP) selectedPackages.joinToString(",") else null,
                                regexPattern = regexPattern.ifBlank { ".*" },
                                httpUrl = httpUrl.trim(),
                                httpMethod = httpMethod,
                                headersJson = headersJson,
                                bodyTemplate = bodyTemplate
                            )
                            onSaveRule(newRule)
                        },
                        colors = ButtonDefaults.buttonColors(containerColor = PrimaryBlue),
                        modifier = Modifier.padding(end = 8.dp)
                    ) {
                        Icon(Icons.Default.Check, contentDescription = null, modifier = Modifier.size(18.dp))
                        Spacer(modifier = Modifier.width(4.dp))
                        Text("Guardar")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = BackgroundDark)
            )
        },
        containerColor = BackgroundDark
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
        ) {
            // Tab Header
            TabRow(
                selectedTabIndex = selectedTab,
                containerColor = CardBackground,
                contentColor = PrimaryBlue
            ) {
                Tab(
                    selected = selectedTab == 0,
                    onClick = { selectedTab = 0 },
                    text = { Text("General", fontWeight = FontWeight.Bold) }
                )
                Tab(
                    selected = selectedTab == 1,
                    onClick = { selectedTab = 1 },
                    text = { Text("Headers (${headerInputs.size})", fontWeight = FontWeight.Bold) }
                )
                Tab(
                    selected = selectedTab == 2,
                    onClick = { selectedTab = 2 },
                    text = { Text("Body ($bodyFormat)", fontWeight = FontWeight.Bold) }
                )
            }

            // Tab Content
            Box(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(16.dp)
            ) {
                when (selectedTab) {
                    0 -> GeneralTabContent(
                        ruleName = ruleName,
                        onNameChange = { ruleName = it },
                        ruleSource = ruleSource,
                        onSourceChange = { ruleSource = it },
                        selectedPackages = selectedPackages,
                        onOpenAppPicker = { showAppPicker = true },
                        regexPattern = regexPattern,
                        onRegexChange = { regexPattern = it },
                        httpUrl = httpUrl,
                        onUrlChange = { httpUrl = it },
                        httpMethod = httpMethod,
                        onMethodChange = { httpMethod = it }
                    )
                    1 -> HeadersTabContent(
                        headerInputs = headerInputs,
                        onAddHeader = {
                            headerInputs.add(HeaderInput(nextHeaderId++, "", ""))
                        },
                        onRemoveHeader = { item ->
                            headerInputs.remove(item)
                        }
                    )
                    2 -> BodyTabContent(
                        bodyFormat = bodyFormat,
                        onFormatChange = { newFormat ->
                            bodyFormat = newFormat
                            updateContentType(newFormat)
                        },
                        bodyTemplate = bodyTemplate,
                        onBodyChange = { bodyTemplate = it }
                    )
                }
            }
        }
    }

    if (showAppPicker) {
        AppPickerDialog(
            currentlySelected = selectedPackages,
            onDismiss = { showAppPicker = false },
            onConfirm = { updatedSet ->
                selectedPackages = updatedSet
                showAppPicker = false
            }
        )
    }
}

// --- TAB GENERAL ---
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun GeneralTabContent(
    ruleName: String,
    onNameChange: (String) -> Unit,
    ruleSource: RuleSource,
    onSourceChange: (RuleSource) -> Unit,
    selectedPackages: Set<String>,
    onOpenAppPicker: () -> Unit,
    regexPattern: String,
    onRegexChange: (String) -> Unit,
    httpUrl: String,
    onUrlChange: (String) -> Unit,
    httpMethod: String,
    onMethodChange: (String) -> Unit
) {
    var expandedMethodDropdown by remember { mutableStateOf(false) }
    val availableMethods = listOf("GET", "POST", "PUT", "DELETE", "HEAD", "PATCH", "OPTIONS")

    LazyColumn(
        modifier = Modifier.fillMaxSize(),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        item {
            OutlinedTextField(
                value = ruleName,
                onValueChange = onNameChange,
                label = { Text("Nombre de la Regla *") },
                supportingText = { Text("Obligatorio (autogenerado por defecto)") },
                modifier = Modifier.fillMaxWidth(),
                colors = OutlinedTextFieldDefaults.colors(focusedBorderColor = PrimaryBlue)
            )
        }

        item {
            Text("Origen del Evento", fontWeight = FontWeight.Bold, color = PrimaryBlue, fontSize = 14.sp)
            Spacer(modifier = Modifier.height(4.dp))
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                FilterChip(
                    selected = ruleSource == RuleSource.APP,
                    onClick = { onSourceChange(RuleSource.APP) },
                    label = { Text("Aplicaciones") },
                    colors = FilterChipDefaults.filterChipColors(
                        selectedContainerColor = PrimaryBlue,
                        selectedLabelColor = Color.White
                    ),
                    modifier = Modifier.weight(1f)
                )
                FilterChip(
                    selected = ruleSource == RuleSource.SMS,
                    onClick = { onSourceChange(RuleSource.SMS) },
                    label = { Text("SMS Interceptor") },
                    colors = FilterChipDefaults.filterChipColors(
                        selectedContainerColor = PrimaryBlue,
                        selectedLabelColor = Color.White
                    ),
                    modifier = Modifier.weight(1f)
                )
            }
        }

        if (ruleSource == RuleSource.APP) {
            item {
                Card(
                    modifier = Modifier
                        .fillMaxWidth()
                        .clickable { onOpenAppPicker() },
                    colors = CardDefaults.cardColors(containerColor = CardBackground),
                    shape = RoundedCornerShape(8.dp)
                ) {
                    Column(modifier = Modifier.padding(14.dp)) {
                        Text("Aplicaciones Seleccionadas", fontWeight = FontWeight.Bold, color = TextLight, fontSize = 14.sp)
                        Spacer(modifier = Modifier.height(4.dp))
                        if (selectedPackages.isEmpty()) {
                            Text("Click para seleccionar apps instaladas (Todas por defecto)", color = TextGray, fontSize = 13.sp)
                        } else {
                            Text(
                                text = "${selectedPackages.size} app(s): ${selectedPackages.joinToString(", ")}",
                                color = PrimaryBlue,
                                fontSize = 13.sp,
                                fontWeight = FontWeight.SemiBold
                            )
                        }
                    }
                }
            }
        }

        item {
            OutlinedTextField(
                value = regexPattern,
                onValueChange = onRegexChange,
                label = { Text("Filtro Expresión Regular (RegEx)") },
                supportingText = { Text("Ejemplo: .*urgente.* o .*OTP.*") },
                modifier = Modifier.fillMaxWidth(),
                colors = OutlinedTextFieldDefaults.colors(focusedBorderColor = PrimaryBlue)
            )
        }

        item {
            OutlinedTextField(
                value = httpUrl,
                onValueChange = onUrlChange,
                label = { Text("URL Destino HTTP *") },
                modifier = Modifier.fillMaxWidth(),
                colors = OutlinedTextFieldDefaults.colors(focusedBorderColor = PrimaryBlue)
            )
        }

        item {
            Text("Método HTTP", fontWeight = FontWeight.Bold, color = PrimaryBlue, fontSize = 14.sp)
            Spacer(modifier = Modifier.height(4.dp))

            ExposedDropdownMenuBox(
                expanded = expandedMethodDropdown,
                onExpandedChange = { expandedMethodDropdown = !expandedMethodDropdown }
            ) {
                OutlinedTextField(
                    value = httpMethod,
                    onValueChange = {},
                    readOnly = true,
                    label = { Text("Método") },
                    trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = expandedMethodDropdown) },
                    modifier = Modifier
                        .menuAnchor()
                        .fillMaxWidth(),
                    colors = OutlinedTextFieldDefaults.colors(focusedBorderColor = PrimaryBlue)
                )
                ExposedDropdownMenu(
                    expanded = expandedMethodDropdown,
                    onDismissRequest = { expandedMethodDropdown = false }
                ) {
                    availableMethods.forEach { method ->
                        DropdownMenuItem(
                            text = { Text(method, fontWeight = FontWeight.Bold) },
                            onClick = {
                                onMethodChange(method)
                                expandedMethodDropdown = false
                            }
                        )
                    }
                }
            }
        }
    }
}

// --- TAB HEADERS ---
@Composable
fun HeadersTabContent(
    headerInputs: List<HeaderInput>,
    onAddHeader: () -> Unit,
    onRemoveHeader: (HeaderInput) -> Unit
) {
    val suggestions = listOf(
        "{not_title}",
        "{not_text}",
        "{package_name}",
        "{timestamp}",
        "{global_API_KEY}"
    )

    Column(modifier = Modifier.fillMaxSize()) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Text("Cabeceras HTTP", fontWeight = FontWeight.Bold, color = PrimaryBlue, fontSize = 16.sp)
            Button(
                onClick = onAddHeader,
                colors = ButtonDefaults.buttonColors(containerColor = PrimaryBlue),
                contentPadding = PaddingValues(horizontal = 12.dp, vertical = 6.dp)
            ) {
                Icon(Icons.Default.Add, contentDescription = null, modifier = Modifier.size(16.dp))
                Spacer(modifier = Modifier.width(4.dp))
                Text("Añadir Header", fontSize = 13.sp)
            }
        }

        Spacer(modifier = Modifier.height(12.dp))

        if (headerInputs.isEmpty()) {
            Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                Text("No hay cabeceras añadidas. Pulsa 'Añadir Header'.", color = TextGray)
            }
        } else {
            LazyColumn(
                modifier = Modifier.fillMaxSize(),
                verticalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                items(headerInputs, key = { it.id }) { item ->
                    HeaderInputRow(
                        item = item,
                        suggestions = suggestions,
                        onRemove = { onRemoveHeader(item) }
                    )
                }
            }
        }
    }
}

@Composable
fun HeaderInputRow(
    item: HeaderInput,
    suggestions: List<String>,
    onRemove: () -> Unit
) {
    var keyText by remember(item.id) { mutableStateOf(item.key) }
    var valueText by remember(item.id) { mutableStateOf(item.value) }
    var showValueSuggestions by remember { mutableStateOf(false) }

    // Filter suggestions based on value input (max 4 suggestions)
    val filteredSuggestions = remember(valueText) {
        if (valueText.isBlank()) {
            suggestions.take(4)
        } else {
            suggestions.filter { it.contains(valueText, ignoreCase = true) }.take(4)
        }
    }

    Card(
        modifier = Modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(containerColor = CardBackground),
        shape = RoundedCornerShape(8.dp)
    ) {
        Column(modifier = Modifier.padding(10.dp)) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                OutlinedTextField(
                    value = keyText,
                    onValueChange = {
                        keyText = it
                        item.key = it
                    },
                    label = { Text("Header Key") },
                    placeholder = { Text("Content-Type") },
                    modifier = Modifier.weight(1f),
                    colors = OutlinedTextFieldDefaults.colors(focusedBorderColor = PrimaryBlue)
                )

                OutlinedTextField(
                    value = valueText,
                    onValueChange = {
                        valueText = it
                        item.value = it
                        showValueSuggestions = true
                    },
                    label = { Text("Value") },
                    placeholder = { Text("application/json") },
                    modifier = Modifier.weight(1.2f),
                    colors = OutlinedTextFieldDefaults.colors(focusedBorderColor = PrimaryBlue)
                )

                IconButton(onClick = onRemove) {
                    Icon(Icons.Default.Delete, contentDescription = "Eliminar", tint = Color.Red)
                }
            }

            // Autocomplete Suggestion Chips (Max 4)
            if (showValueSuggestions && filteredSuggestions.isNotEmpty()) {
                Spacer(modifier = Modifier.height(6.dp))
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(6.dp)
                ) {
                    filteredSuggestions.forEach { suggestion ->
                        SuggestionChip(
                            onClick = {
                                valueText = suggestion
                                item.value = suggestion
                                showValueSuggestions = false
                            },
                            label = { Text(suggestion, fontSize = 11.sp, color = PrimaryBlue) },
                            colors = SuggestionChipDefaults.suggestionChipColors(containerColor = PrimaryLightBlue.copy(alpha = 0.15f))
                        )
                    }
                }
            }
        }
    }
}

// --- TAB BODY ---
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun BodyTabContent(
    bodyFormat: String,
    onFormatChange: (String) -> Unit,
    bodyTemplate: String,
    onBodyChange: (String) -> Unit
) {
    Column(modifier = Modifier.fillMaxSize()) {
        Text("Formato del Payload", fontWeight = FontWeight.Bold, color = PrimaryBlue, fontSize = 16.sp)
        Spacer(modifier = Modifier.height(6.dp))

        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            FilterChip(
                selected = bodyFormat == "JSON",
                onClick = { onFormatChange("JSON") },
                label = { Text("JSON (application/json)") },
                colors = FilterChipDefaults.filterChipColors(
                    selectedContainerColor = PrimaryBlue,
                    selectedLabelColor = Color.White
                ),
                modifier = Modifier.weight(1f)
            )
            FilterChip(
                selected = bodyFormat == "TEXT",
                onClick = { onFormatChange("TEXT") },
                label = { Text("Texto Plano (text/plain)") },
                colors = FilterChipDefaults.filterChipColors(
                    selectedContainerColor = PrimaryBlue,
                    selectedLabelColor = Color.White
                ),
                modifier = Modifier.weight(1f)
            )
        }

        Spacer(modifier = Modifier.height(12.dp))
        Text("Editor del Cuerpo (Body Template):", fontWeight = FontWeight.SemiBold, fontSize = 14.sp, color = TextLight)
        Spacer(modifier = Modifier.height(4.dp))

        OutlinedTextField(
            value = bodyTemplate,
            onValueChange = onBodyChange,
            modifier = Modifier
                .fillMaxWidth()
                .weight(1f),
            textStyle = LocalTextStyle.current.copy(fontFamily = FontFamily.Monospace, fontSize = 13.sp),
            placeholder = { Text(if (bodyFormat == "JSON") "{\n  \"key\": \"value\"\n}" else "Escribe tu plantilla...") },
            colors = OutlinedTextFieldDefaults.colors(
                focusedBorderColor = PrimaryBlue,
                unfocusedContainerColor = Color.Black.copy(alpha = 0.3f),
                focusedContainerColor = Color.Black.copy(alpha = 0.5f)
            )
        )

        Spacer(modifier = Modifier.height(8.dp))
        Text(
            text = "Variables disponibles: {not_title}, {not_text}, {package_name}, {timestamp}, {global_NOMBRE}",
            fontSize = 11.sp,
            color = TextGray
        )
    }
}

// --- APP PICKER DIALOG ---
@Composable
fun AppPickerDialog(
    currentlySelected: Set<String>,
    onDismiss: () -> Unit,
    onConfirm: (Set<String>) -> Unit
) {
    val context = LocalContext.current
    var searchQuery by remember { mutableStateOf("") }
    val tempSelected = remember { mutableStateListOf<String>().apply { addAll(currentlySelected) } }

    val installedApps = remember {
        val pm = context.packageManager
        val packages = pm.getInstalledApplications(PackageManager.GET_META_DATA)
        packages.map { app ->
            AppItemInfo(
                label = pm.getApplicationLabel(app).toString(),
                packageName = app.packageName
            )
        }.sortedBy { it.label.lowercase() }
    }

    val filteredApps = remember(searchQuery, installedApps) {
        if (searchQuery.isBlank()) {
            installedApps
        } else {
            installedApps.filter {
                it.label.contains(searchQuery, ignoreCase = true) || it.packageName.contains(searchQuery, ignoreCase = true)
            }
        }
    }

    Dialog(onDismissRequest = onDismiss) {
        Card(
            modifier = Modifier
                .fillMaxWidth()
                .fillMaxHeight(0.85f),
            shape = RoundedCornerShape(16.dp),
            colors = CardDefaults.cardColors(containerColor = CardBackground)
        ) {
            Column(
                modifier = Modifier
                    .padding(16.dp)
                    .fillMaxSize()
            ) {
                Text("Seleccionar Aplicaciones", fontSize = 18.sp, fontWeight = FontWeight.Bold, color = PrimaryBlue)
                Spacer(modifier = Modifier.height(8.dp))

                OutlinedTextField(
                    value = searchQuery,
                    onValueChange = { searchQuery = it },
                    placeholder = { Text("Buscar aplicación o paquete...") },
                    leadingIcon = { Icon(Icons.Default.Search, contentDescription = null) },
                    modifier = Modifier.fillMaxWidth(),
                    colors = OutlinedTextFieldDefaults.colors(focusedBorderColor = PrimaryBlue)
                )

                Spacer(modifier = Modifier.height(8.dp))

                LazyColumn(
                    modifier = Modifier.weight(1f),
                    verticalArrangement = Arrangement.spacedBy(4.dp)
                ) {
                    items(filteredApps, key = { it.packageName }) { app ->
                        val isChecked = tempSelected.contains(app.packageName)
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .clickable {
                                    if (isChecked) {
                                        tempSelected.remove(app.packageName)
                                    } else {
                                        tempSelected.add(app.packageName)
                                    }
                                }
                                .padding(vertical = 8.dp, horizontal = 4.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Checkbox(
                                checked = isChecked,
                                onCheckedChange = { checked ->
                                    if (checked) {
                                        tempSelected.add(app.packageName)
                                    } else {
                                        tempSelected.remove(app.packageName)
                                    }
                                },
                                colors = CheckboxDefaults.colors(checkedColor = PrimaryBlue)
                            )
                            Spacer(modifier = Modifier.width(8.dp))
                            Column {
                                Text(app.label, fontWeight = FontWeight.SemiBold, fontSize = 14.sp, color = TextLight)
                                Text(app.packageName, fontSize = 12.sp, color = TextGray)
                            }
                        }
                    }
                }

                Spacer(modifier = Modifier.height(8.dp))
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.End
                ) {
                    TextButton(onClick = onDismiss) { Text("Cancelar", color = TextGray) }
                    Spacer(modifier = Modifier.width(8.dp))
                    Button(
                        onClick = { onConfirm(tempSelected.toSet()) },
                        colors = ButtonDefaults.buttonColors(containerColor = PrimaryBlue)
                    ) {
                        Text("Aceptar (${tempSelected.size})")
                    }
                }
            }
        }
    }
}
